import GoblinPattern from "@/Enemies/GoblinPattern.vue";
import SkeletonPattern from "@/Enemies/SkeletonPattern.vue";

export const enemies = [
    {
        name: "Goblin",
        health: 10,
        maxhealth: 10,
        speed: 1,
        level: 1,
        damage: 5,
        mana: 0,
        maxmana: 0,
        healthregen: 1,
        manaregen: 0,
        mindamage: 1,
        maxdamage: 6,
        ability: 1,
        output: 1,
        image: "",
        color: "",
        type: "humanoid",
        passives: [],
        pattern: GoblinPattern,
        attributes: {
            strength: 4,
            agility: 6,
            intelligence: 2,
        },
    },
    {
        name: "Skeleton",
        health: 15,
        maxhealth: 15,
        speed: 1.2,
        level: 2,
        damage: 6,
        mana: 5,
        maxmana: 20,
        healthregen: 1,
        manaregen: 1,
        mindamage: 2,
        maxdamage: 8,
        ability: 1,
        output: 1,
        image: "",
        color: "",
        type: "undead",
        passives: [],
        pattern: SkeletonPattern,
        attributes: {
            strength: 5,
            agility: 4,
            intelligence: 3,
        },
    },
    {
        name: "Orc",
        health: 25,
        maxhealth: 25,
        speed: 0.9,
        level: 3,
        damage: 10,
        mana: 0,
        maxmana: 0,
        healthregen: 2,
        manaregen: 0,
        mindamage: 3,
        maxdamage: 12,
        ability: 1,
        output: 1,
        image: "",
        color: "",
        type: "humanoid",
        passives: [],
        pattern: null,
        attributes: {
            strength: 8,
            agility: 3,
            intelligence: 2,
        },
    },
    {
        name: "Dark Mage",
        health: 18,
        maxhealth: 18,
        speed: 1.1,
        level: 4,
        damage: 12,
        mana: 20,
        maxmana: 40,
        healthregen: 1,
        manaregen: 2,
        mindamage: 4,
        maxdamage: 15,
        ability: 2,
        output: 2,
        image: "",
        color: "",
        type: "humanoid",
        passives: [],
        pattern: null,
        attributes: {
            strength: 2,
            agility: 4,
            intelligence: 9,
        },
    },
    {
        name: "Giant Spider",
        health: 20,
        maxhealth: 20,
        speed: 1.5,
        level: 5,
        damage: 8,
        mana: 0,
        maxmana: 0,
        healthregen: 2,
        manaregen: 0,
        mindamage: 3,
        maxdamage: 10,
        ability: 1,
        output: 1,
        image: "",
        color: "",
        type: "beast",
        passives: [],
        pattern: null,
        attributes: {
            strength: 6,
            agility: 8,
            intelligence: 1,
        },
    },
    {
        name: "Troll",
        health: 40,
        maxhealth: 40,
        speed: 0.7,
        level: 6,
        damage: 15,
        mana: 5,
        maxmana: 20,
        healthregen: 3,
        manaregen: 1,
        mindamage: 5,
        maxdamage: 18,
        ability: 1,
        output: 1,
        image: "",
        color: "",
        type: "beast",
        passives: [],
        pattern: null,
        attributes: {
            strength: 10,
            agility: 2,
            intelligence: 1,
        },
    },
    {
        name: "Wraith",
        health: 22,
        maxhealth: 22,
        speed: 1.8,
        level: 7,
        damage: 10,
        mana: 10,
        maxmana: 30,
        healthregen: 1,
        manaregen: 3,
        mindamage: 4,
        maxdamage: 12,
        ability: 1,
        output: 2,
        image: "",
        color: "",
        type: "undead",
        passives: [],
        pattern: null,
        attributes: {
            strength: 4,
            agility: 9,
            intelligence: 6,
        },
    },
    {
        name: "Demon Hound",
        health: 30,
        maxhealth: 30,
        speed: 2,
        level: 8,
        damage: 14,
        mana: 10,
        maxmana: 25,
        healthregen: 2,
        manaregen: 2,
        mindamage: 5,
        maxdamage: 15,
        ability: 2,
        output: 2,
        image: "",
        color: "",
        type: "demon",
        passives: [],
        pattern: null,
        attributes: {
            strength: 7,
            agility: 10,
            intelligence: 2,
        },
    },
    {
        name: "Necromancer",
        health: 35,
        maxhealth: 35,
        speed: 1.2,
        level: 9,
        damage: 18,
        mana: 20,
        maxmana: 50,
        healthregen: 1,
        manaregen: 4,
        mindamage: 6,
        maxdamage: 20,
        ability: 2,
        output: 3,
        image: "",
        color: "",
        type: "undead",
        passives: [],
        pattern: null,
        attributes: {
            strength: 3,
            agility: 5,
            intelligence: 10,
        },
    },
    {
        name: "Dragon",
        health: 100,
        maxhealth: 100,
        speed: 1.5,
        level: 10,
        damage: 30,
        mana: 50,
        maxmana: 100,
        healthregen: 5,
        manaregen: 5,
        mindamage: 10,
        maxdamage: 40,
        ability: 3,
        output: 5,
        image: "",
        color: "",
        type: "dragon",
        passives: [],
        pattern: null,
        attributes: {
            strength: 15,
            agility: 6,
            intelligence: 8,
        },
    }
];
