export const enemies = [
    {
        name: "Goblin",
        health: 10,
        speed: 1,
        level: 1,
        damage: 5,
        image: "",
        color: "",
        type: "humanoid",
        passives: [],
        attributes: {
            strength: 4,
            agility: 6,
            intelligence: 2,
        },
    },
    {
        name: "Skeleton",
        health: 15,
        speed: 1.2,
        level: 2,
        damage: 6,
        image: "",
        color: "",
        type: "undead",
        passives: [],
        attributes: {
            strength: 5,
            agility: 4,
            intelligence: 3,
        },
    },
    {
        name: "Orc",
        health: 25,
        speed: 0.9,
        level: 3,
        damage: 10,
        image: "",
        color: "",
        type: "humanoid",
        passives: [],
        attributes: {
            strength: 8,
            agility: 3,
            intelligence: 2,
        },
    },
    {
        name: "Dark Mage",
        health: 18,
        speed: 1.1,
        level: 4,
        damage: 12,
        image: "",
        color: "",
        type: "humanoid",
        passives: [],
        attributes: {
            strength: 2,
            agility: 4,
            intelligence: 9,
        },
    },
    {
        name: "Giant Spider",
        health: 20,
        speed: 1.5,
        level: 5,
        damage: 8,
        image: "",
        color: "",
        type: "beast",
        passives: [],
        attributes: {
            strength: 6,
            agility: 8,
            intelligence: 1,
        },
    },
    {
        name: "Troll",
        health: 40,
        speed: 0.7,
        level: 6,
        damage: 15,
        image: "",
        color: "",
        type: "beast",
        passives: [],
        attributes: {
            strength: 10,
            agility: 2,
            intelligence: 1,
        },
    },
    {
        name: "Wraith",
        health: 22,
        speed: 1.8,
        level: 7,
        damage: 10,
        image: "",
        color: "",
        type: "undead",
        passives: [],
        attributes: {
            strength: 4,
            agility: 9,
            intelligence: 6,
        },
    },
    {
        name: "Demon Hound",
        health: 30,
        speed: 2,
        level: 8,
        damage: 14,
        image: "",
        color: "",
        type: "demon",
        passives: [],
        attributes: {
            strength: 7,
            agility: 10,
            intelligence: 2,
        },
    },
    {
        name: "Necromancer",
        health: 35,
        speed: 1.2,
        level: 9,
        damage: 18,
        image: "",
        color: "",
        type: "undead",
        passives: [],
        attributes: {
            strength: 3,
            agility: 5,
            intelligence: 10,
        },
    },
    {
        name: "Dragon",
        health: 100,
        speed: 1.5,
        level: 10,
        damage: 30,
        image: "",
        color: "",
        type: "dragon",
        passives: [],
        attributes: {
            strength: 15,
            agility: 6,
            intelligence: 8,
        },
    }
];